"""da_learn - English practice copy of a SUBSET of classificacao_vendas/
data_app_gestao.py (the "gestao" Streamlit data app from the
analise_representante project): 660 Analysis (+ Churns in the Month),
Rises and Drops, and Rep Block Performance (Doctor Potential only).

Runs 100% local, no login, no Supabase - reads from the ANONYMIZED parquet
files under data/ (generated by anonymize/anonymize_data.py from the real
bases_cprata bases; see that script's docstring and README.md). All the
calculation logic lives in transform.py, in this same folder - this file
is only the UI (pages + widgets + formatting).

Usage (from this folder):
    streamlit run data_app_gestao.py
"""

from __future__ import annotations

import pandas as pd
import streamlit as st

import transform

st.set_page_config(page_title="Sales Classification (Practice Copy)", layout="wide")

PAYMENT_TYPES = ["Own Funds", "Legal", "All"]
CUTOFFS_PCT = {"10%": 10.0, "5%": 5.0, "4%": 4.0, "3%": 3.0, "1%": 1.0, "All": None}

_NUMBER_COLUMN = st.column_config.NumberColumn(format="%,.2f")
_UNITS_COLUMN = st.column_config.NumberColumn(format="%,d")
_CURRENCY_COLUMN = st.column_config.NumberColumn(format="R$ %,.2f")
_PERCENT_COLUMN = st.column_config.NumberColumn(format="%.1f%%")
_MONTH_COLUMN = st.column_config.DateColumn(format="MM/YYYY")


def format_currency(value) -> str:
    if value is None or pd.isna(value):
        return "-"
    text = f"{value:,.2f}"
    return "R$ " + text.replace(",", "X").replace(".", ",").replace("X", ".")


def format_integer(value) -> str:
    if value is None or pd.isna(value):
        return "-"
    return str(int(round(value)))


@st.cache_data(ttl=600)
def _cached_data_660():
    return transform.load_data_660()


@st.cache_data(ttl=600)
def _cached_data_churns():
    return transform.load_data_churns()


@st.cache_data(ttl=600)
def _cached_data_doctor_potential():
    return transform.load_data_doctor_potential()


def _select_metric(key: str):
    return st.selectbox(
        "Metric", list(transform.NAME_METRIC.keys()), format_func=lambda m: transform.NAME_METRIC[m], key=key,
    )


def _select_month_selection(column, key_prefix: str) -> transform.MonthSelection:
    """"Month Selection" segmenter - next to "Benchmark Period". Lets you
    benchmark against the BEST months in the window instead of the
    average of all of them."""
    kind_label = column.selectbox(
        "Month Selection", ["All", "Top N Months", "Top % Months"], key=f"{key_prefix}_kind",
        help=(
            '"All" uses the whole benchmark window (default). "Top N/Top %" restricts the mean/median '
            "to only the HIGHEST-value months in that window - a benchmark against the best months, "
            "instead of the average of everything."
        ),
    )
    if kind_label == "Top N Months":
        value = st.number_input(
            "How many months (highest to lowest)", min_value=1, max_value=999, value=12, step=1,
            key=f"{key_prefix}_value_n",
        )
        return transform.MonthSelection("top_n", value)
    if kind_label == "Top % Months":
        value = st.number_input(
            "Which % of months (highest to lowest)", min_value=1, max_value=100, value=25, step=1,
            key=f"{key_prefix}_value_pct",
        )
        return transform.MonthSelection("top_pct", value)
    return transform.MonthSelection("all")


def _select_months_in_current_period(column, key: str) -> int:
    return column.number_input(
        "Months in Current Period", min_value=1, max_value=36, value=1, step=1, key=key,
        help=(
            'How many months to sum into "now": the chosen month plus the N-1 months right before it. '
            '"Current Value" becomes the MEAN (or median, per "Summary Measure" below) of those N '
            "months - not their total - so it can come out LOWER than looking at a single month, if the "
            "months before the chosen one were weaker than it."
        ),
    )


def _current_period_label(measure: str, months_in_current_period: int) -> str:
    return "Current Value" if months_in_current_period <= 1 else f"Current Value ({measure})"


def _current_period_explanation(measure: str, months_in_current_period: int) -> str | None:
    if months_in_current_period <= 1:
        return None
    return (
        f'**Months in Current Period = {months_in_current_period}:** "Current Value" is now the '
        f"**{measure.lower()}** (not the sum) of those {months_in_current_period} months - the chosen "
        f"month plus the {months_in_current_period - 1} months right before it. If the months before "
        "the chosen one were weaker, the value drops versus looking at 1 month alone (and rises if they "
        "were stronger) - that is expected, not an error. The **Benchmark** also now ends before that "
        "whole period, not just before the chosen month, so the same months are never counted twice."
    )


def _value_config(metric: str) -> dict:
    return _CURRENCY_COLUMN if metric == "revenue" else _UNITS_COLUMN


# ---------------------------------------------------------------------------
# 660 Analysis
# ---------------------------------------------------------------------------

def page_660_analysis() -> None:
    st.header("660 Analysis")
    st.caption(
        "Own-brand internal sales compared against a retroactive benchmark window (excludes the "
        "current period), classified by % deviation."
    )

    data = _cached_data_660()
    blocks = transform.blocks_available(data)
    months = transform.months_available(data)
    if not blocks or not months:
        st.info("Not enough own-brand sales data for this analysis.")
        return

    c1, c2, c3, c4, c5 = st.columns(5)
    block_label = c1.selectbox("Block", ["All"] + blocks, index=0, key="block_660")
    block = None if block_label == "All" else block_label
    month = c2.selectbox(
        "Month", months, index=len(months) - 1, format_func=lambda m: m.strftime("%m/%Y"), key="month_660",
    )
    months_in_current_period = _select_months_in_current_period(c3, "months_current_660")
    client_effort = c4.radio("Client Effort", ["Yes", "All"], horizontal=True, key="effort_660")
    payment_type = c5.selectbox("Payment Type", PAYMENT_TYPES, index=2, key="payment_660")

    c6, c7, c8 = st.columns(3)
    window = c6.selectbox("Benchmark Period", list(transform.BENCHMARK_WINDOWS.keys()), key="window_660")
    measure = c7.radio("Summary Measure", ["Mean", "Median"], horizontal=True, key="measure_660")
    selection = _select_month_selection(c8, "selection_660")

    explanation = _current_period_explanation(measure, months_in_current_period)
    if explanation is not None:
        st.info(explanation)

    table = transform.calculate_table_660(
        data, block, client_effort, payment_type, month, window, measure, selection, months_in_current_period,
    )
    exibir = pd.DataFrame({
        "Metric": table["metric"].map(transform.NAME_METRIC),
        _current_period_label(measure, months_in_current_period): table["current_value"],
        f"Benchmark ({measure})": table["benchmark"],
        "Classification": table["classification"],
    })
    st.dataframe(
        exibir, use_container_width=True, hide_index=True,
        column_config={
            _current_period_label(measure, months_in_current_period): _NUMBER_COLUMN,
            f"Benchmark ({measure})": _NUMBER_COLUMN,
        },
    )

    st.subheader("By Sale Type")
    metric_tv = _select_metric("metric_tv_660")
    table_tv = transform.calculate_table_by_sale_type(
        data, block, client_effort, payment_type, month, window, measure, metric_tv, selection, months_in_current_period,
    )
    exibir_tv = pd.DataFrame({
        "Sale Type": table_tv["sale_type"],
        _current_period_label(measure, months_in_current_period): table_tv["current_value"],
        f"Benchmark ({measure})": table_tv["benchmark"],
        "Difference": table_tv["difference"],
        "Classification": table_tv["classification"],
    })
    value_col = _value_config(metric_tv)
    st.dataframe(
        exibir_tv, use_container_width=True, hide_index=True,
        column_config={
            _current_period_label(measure, months_in_current_period): value_col,
            f"Benchmark ({measure})": value_col, "Difference": value_col,
        },
    )

    st.subheader("By Doctor")
    cm1, cm2 = st.columns(2)
    metric_med = cm1.selectbox(
        "Metric", list(transform.NAME_METRIC.keys()), format_func=lambda m: transform.NAME_METRIC[m], key="metric_doctor_660",
    )
    sale_type_label = cm2.selectbox(
        "Sale Type", ["All"] + transform.sale_types_available(data), index=0, key="sale_type_doctor_660",
    )
    sale_type = None if sale_type_label == "All" else sale_type_label
    table_med = transform.calculate_table_by_doctor(
        data, block, client_effort, payment_type, sale_type, month, window, measure, metric_med, selection,
        months_in_current_period,
    )
    if table_med.empty:
        st.info("No doctor with sales in the selected scope.")
    else:
        exibir_med = pd.DataFrame({
            "Doctor": table_med["doctor_name"],
            "CRM-UF": table_med["crm_uf"],
            "Blocks": table_med["blocks"],
            _current_period_label(measure, months_in_current_period): table_med["current_value"],
            f"Benchmark ({measure})": table_med["benchmark"],
            "Difference": table_med["difference"],
            "Classification": table_med["classification"],
        })
        value_col_med = _value_config(metric_med)
        st.dataframe(
            exibir_med, use_container_width=True, hide_index=True,
            column_config={
                _current_period_label(measure, months_in_current_period): value_col_med,
                f"Benchmark ({measure})": value_col_med, "Difference": value_col_med,
            },
        )

    st.subheader("By Product")
    st.caption(
        "Search a doctor's CRM-UF (as it appears in \"By Doctor\" above) to see the drop/rise "
        "product by product - sums every block where that CRM-UF appears, ignoring the \"Block\" "
        "segmenter at the top of the page."
    )
    crm_uf_product = st.text_input("Doctor CRM-UF", key="crm_uf_product_660")
    metric_product = _select_metric("metric_product_660")
    if not crm_uf_product.strip():
        st.caption("Type a CRM-UF above to see the products.")
    else:
        table_product = transform.calculate_table_by_product(
            data, crm_uf_product, client_effort, payment_type, month, window, measure, metric_product,
            selection, months_in_current_period,
        )
        if table_product.empty:
            st.info("No sales for this doctor in the selected scope.")
        else:
            exibir_product = pd.DataFrame({
                "Product": table_product["product"],
                _current_period_label(measure, months_in_current_period): table_product["current_value"],
                f"Benchmark ({measure})": table_product["benchmark"],
                "Difference": table_product["difference"],
                "Classification": table_product["classification"],
            })
            value_col_product = _value_config(metric_product)
            st.dataframe(
                exibir_product, use_container_width=True, hide_index=True,
                column_config={
                    _current_period_label(measure, months_in_current_period): value_col_product,
                    f"Benchmark ({measure})": value_col_product, "Difference": value_col_product,
                },
            )

    st.subheader("Churns in the Month")
    st.caption(
        f"Patients whose projected stock rupture (last own-brand purchase - any product) falls in "
        f"{month:%m/%Y}. Excludes patients flagged as a posologia outlier (POSOLOGIA_SUSPEITA, a "
        "single upper Tukey fence computed upstream per product)."
    )
    churn_data = _cached_data_churns()
    cc1, cc2, cc3 = st.columns(3)
    product_label = cc1.selectbox(
        "Product", ["All"] + transform.products_available_churns(churn_data), key="product_churns",
    )
    product = None if product_label == "All" else product_label
    block_churn_label = cc2.selectbox(
        "Block", ["All"] + transform.blocks_available_churns(churn_data), key="block_churns",
    )
    block_churn = None if block_churn_label == "All" else block_churn_label
    payment_churns = cc3.selectbox("Payment Type", PAYMENT_TYPES, index=2, key="payment_churns")

    result = transform.calculate_churns_in_month(churn_data, month, product, block_churn, payment_churns)
    st.metric("Churns (excluding posologia outliers)", format_integer(result["churn_count"]))
    st.dataframe(result["table"], use_container_width=True, hide_index=True)


# ---------------------------------------------------------------------------
# Rises and Drops
# ---------------------------------------------------------------------------

def _display_ranking(table: pd.DataFrame, metric: str, value_label: str, percent_label: str, include_sale_type: bool = True) -> None:
    if table.empty:
        st.info("No combination reached the selected cutoff in this scope.")
        return
    columns = {"Block": table["block"]}
    if include_sale_type:
        columns["Sale Type"] = table["sale_type"]
    columns["Current Value"] = table["current_value"]
    columns["Benchmark"] = table["benchmark"]
    columns["Classification"] = table["classification"]
    columns[value_label] = table["magnitude"]
    columns[percent_label] = table["percentage"]
    exibir = pd.DataFrame(columns)
    value_col = _value_config(metric)
    st.dataframe(
        exibir, use_container_width=True, hide_index=True,
        column_config={
            "Current Value": value_col, "Benchmark": value_col,
            value_label: value_col, percent_label: _PERCENT_COLUMN,
        },
    )


def page_rises_drops() -> None:
    st.header("Rises and Drops")
    st.caption(
        "Biggest rises and drops by block (and by block x sale type), on the chosen metric, comparing "
        "all blocks at once."
    )

    data = _cached_data_660()
    months = transform.months_available(data)
    if not months:
        st.info("Not enough own-brand sales data for this analysis.")
        return

    c1, c2, c3, c4 = st.columns(4)
    month = c1.selectbox("Month", months, index=len(months) - 1, format_func=lambda m: m.strftime("%m/%Y"), key="month_rd")
    months_in_current_period = _select_months_in_current_period(c2, "months_current_rd")
    client_effort = c3.radio("Client Effort", ["Yes", "All"], horizontal=True, key="effort_rd")
    payment_type = c4.selectbox("Payment Type", PAYMENT_TYPES, index=2, key="payment_rd")

    c5, c6 = st.columns(2)
    metric = c5.selectbox(
        "Metric", list(transform.NAME_METRIC.keys()), format_func=lambda m: transform.NAME_METRIC[m], key="metric_rd",
    )
    cutoff_label = c6.selectbox("Show from", list(CUTOFFS_PCT.keys()), index=1, key="cutoff_rd")
    cutoff_pct = CUTOFFS_PCT[cutoff_label]

    c7, c8, c9 = st.columns(3)
    window = c7.selectbox("Benchmark Period", list(transform.BENCHMARK_WINDOWS.keys()), key="window_rd")
    measure = c8.radio("Summary Measure", ["Mean", "Median"], horizontal=True, key="measure_rd")
    selection = _select_month_selection(c9, "selection_rd")

    explanation = _current_period_explanation(measure, months_in_current_period)
    if explanation is not None:
        st.info(explanation)

    base_block = transform.calculate_base_table_by_block(
        data, client_effort, payment_type, month, window, measure, metric, selection, months_in_current_period,
    )
    base_tv = transform.calculate_base_table(
        data, client_effort, payment_type, month, window, measure, metric, selection, months_in_current_period,
    )

    st.subheader("Biggest Drops")
    st.markdown("**Without sale type**")
    _display_ranking(transform.drops(base_block, cutoff_pct), metric, "Drop", "% of Total Drop", include_sale_type=False)
    st.markdown("**By sale type**")
    _display_ranking(transform.drops(base_tv, cutoff_pct), metric, "Drop", "% of Total Drop")

    st.subheader("Biggest Rises")
    st.markdown("**Without sale type**")
    _display_ranking(transform.rises(base_block, cutoff_pct), metric, "Rise", "% of Total Rise", include_sale_type=False)
    st.markdown("**By sale type**")
    _display_ranking(transform.rises(base_tv, cutoff_pct), metric, "Rise", "% of Total Rise")


# ---------------------------------------------------------------------------
# Rep Block Performance - Doctor Potential
# ---------------------------------------------------------------------------

def page_rep_block_performance() -> None:
    st.header("Rep Block Performance")
    st.caption(
        "1st section: Doctor Potential - crosses external market potential (Closeup, PX in the most "
        "recent MAT) with effort (panel presence/visit, classified locally - no external system is "
        "read here) and internal result (1015 revenue)."
    )

    data = _cached_data_doctor_potential()
    blocks = transform.blocks_available_doctor_potential(data)
    if not blocks:
        st.info("Not enough market data (Closeup) for this analysis.")
        return

    mat_text = data.mat_anchor.strftime("%m/%Y") if data.mat_anchor is not None else "-"
    st.caption(
        f"PX in the most recent available MAT ({mat_text}); Result = internal revenue (\"1015 Sales\", "
        "VALOR_REPRESENTANTE) in the same 12-month window ending at the MAT."
    )

    st.subheader("Doctor Potential")
    c1, c2, c3 = st.columns(3)
    block_label = c1.selectbox("Block", ["All"] + blocks, index=0, key="block_doctor_potential")
    block = None if block_label == "All" else block_label
    laboratories = transform.laboratories_available_doctor_potential(data)
    laboratory_label = c2.selectbox("Laboratory", ["All"] + laboratories, index=0, key="laboratory_doctor_potential")
    laboratory = None if laboratory_label == "All" else laboratory_label
    product_type = c3.selectbox("Product Type", ["All", "Isolate", "Full Spectrum"], index=0, key="product_type_doctor_potential")

    c4, c5 = st.columns(2)
    effort = c4.selectbox(
        "Effort", transform.EFFORTS, index=0, key="effort_doctor_potential",
        help=(
            '"Outside Panel": no record for that CRM-UF in the local panel data. "Never Visited": in '
            'the panel, but no visit date on record. "Visited": visited, but more than '
            f'{transform.DAYS_RECENT_VISIT} days ago. "Visited Recently": visited within the last '
            f'{transform.DAYS_RECENT_VISIT} days. Mutually exclusive - every doctor falls into exactly one.'
        ),
    )
    result_label = c5.selectbox(
        "Result", transform.RESULTS, index=0, key="result_doctor_potential",
        help='"No Result" = R$ 0.00 internal revenue in the window; "With Result" = any value above R$ 0.00.',
    )

    table = transform.calculate_table_doctor_potential(data, block, laboratory, product_type, effort, result_label)
    if table.empty:
        st.info("No doctor in the selected scope.")
    else:
        exibir = pd.DataFrame({
            "Doctor": table["doctor_name"],
            "CRM-UF": table["crm_uf"],
            "Blocks": table["blocks"],
            "PX (MAT)": table["px"],
            "Effort": table["effort"],
            "Result": table["result"],
            "Reason": table["reason"],
        })
        st.dataframe(
            exibir, use_container_width=True, hide_index=True,
            column_config={"PX (MAT)": _UNITS_COLUMN, "Result": _CURRENCY_COLUMN},
        )

    st.subheader("By Product")
    st.caption(
        "Search a doctor's CRM-UF (as it appears above) to see PX by laboratory/product in the "
        "market, in the same MAT - Isolate and Full Spectrum together, regardless of the \"Product "
        "Type\" segmenter chosen above."
    )
    crm_uf_potential = st.text_input("Doctor CRM-UF", key="crm_uf_doctor_potential")
    if not crm_uf_potential.strip():
        st.caption("Type a CRM-UF above to see the products.")
    else:
        products = transform.calculate_products_doctor_potential(data, crm_uf_potential)
        if products.empty:
            st.info("No market product found for this CRM-UF in the most recent MAT.")
        else:
            exibir_products = pd.DataFrame({
                "Product": products["product"],
                "Laboratory": products["laboratory"],
                "Product Type": products["product_type"],
                "PX": products["px"],
            })
            st.dataframe(
                exibir_products, use_container_width=True, hide_index=True,
                column_config={"PX": _UNITS_COLUMN},
            )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    navigation = st.navigation([
        st.Page(page_660_analysis, title="660 Analysis", icon="📈", default=True),
        st.Page(page_rises_drops, title="Rises and Drops", icon="📉"),
        st.Page(page_rep_block_performance, title="Rep Block Performance", icon="🧭"),
    ])
    navigation.run()


if __name__ == "__main__":
    main()
