"""Data layer for the da_learn practice copy of "classificacao_vendas"
(the "gestao" data app from analise_representante). English port of a
SUBSET of classificacao_vendas/transform.py: 660 Analysis (+ its Churns in
the Month sub-section), Rises and Drops, and Rep Block Performance (Doctor
Potential only, no Supabase - effort is classified from the LOCAL painel
table instead, see "Rep Block Performance" section below).

Reads from ANONYMIZED parquet files under da_learn/data/ (generated by
anonymize/anonymize_data.py from the real bases in bases_cprata) - never
reads the real bases directly. All business logic/thresholds below are
ported unchanged from classificacao_vendas/transform.py; only naming
(English) and the source schema (new parquet bases, see
limpeza_bases/docs/documentacao_bases.md) changed:
    - TIPO_VENDA used to be computed inside classificacao_vendas/
      transform.py from vendas + posologia; it now comes PRE-COMPUTED from
      tipo_venda.parquet (own base upstream in limpeza_bases since
      2026-10-05) - this port just reads it, no reclassification logic
      here. Bucket granularity is therefore the UPSTREAM one (Acquisition/
      Retention/Late Repurchase/Win-back Inactive 2/Win-back Inactive 3/
      Unclassified/Government Health Dept/Legal, or Not Classified) - NOT
      collapsed into the older Acquisition/Retention/Win-back/Unclassified/
      Government/Legal 4-bucket scheme classificacao_vendas used (that
      scheme pre-dates tipo_venda.parquet's own, more granular one).
    - "Churns in the Month" used to re-derive the stock-rupture projection
      from vendas + posologia (per PATIENT, two IQR outlier tiers); it now
      reads the pre-computed CHURN/DATA_RUPTURA/POSOLOGIA_SUSPEITA columns
      from carteira_pacientes.parquet (own base upstream, one row per SALE
      - CHURN is already True only on each patient's LAST sale, matching
      the old "per patient" semantics) - only ONE outlier tier exists
      upstream (POSOLOGIA_SUSPEITA, a single Tukey fence), not the old
      1.5x/3x IQR pair - the page below shows one count, not two.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

PASTA_DADOS = Path(__file__).resolve().parent / "data"
NOT_INFORMED = "(not informed)"


def _ler(nome: str) -> pd.DataFrame:
    caminho = PASTA_DADOS / f"{nome}.parquet"
    if not caminho.exists():
        raise FileNotFoundError(
            f"{caminho} does not exist - run anonymize/anonymize_data.py first (see README.md)."
        )
    return pd.read_parquet(caminho)


# =============================================================================
# 660 Analysis - own-brand sales (TIPO_REGISTRO starts with "VENDA" AND
# MARCA_PROPRIA==1) vs a retroactive benchmark window, classified by %
# deviation. Ported from classificacao_vendas/transform.py ("Analise 660" +
# "RecorteMeses"/"Meses no periodo atual" features) - same formulas,
# English names, reading the new parquet schema.
# =============================================================================

METRICS = ["revenue", "order_count", "units", "new_patients"]

NAME_METRIC = {
    "revenue": "Revenue (R$)", "order_count": "Order Count", "units": "Units",
    "new_patients": "New Patients",
}

# window, in months, ending right before the "current period" (see
# RecorteMeses/_current_period below) - "Historical" (None) starts at the
# series' own first data point instead of a fixed count.
BENCHMARK_WINDOWS = {"Quarter": 3, "Semester": 6, "Year": 12, "Last 3 Years": 36, "Historical": None}


def _eh_venda(tipo_registro: pd.Series) -> pd.Series:
    """TIPO_REGISTRO starting with "VENDA" (prefix match - also catches a
    literal "VENDA" and any variant the source might use)."""
    return tipo_registro.astype(str).str.upper().str.startswith("VENDA")


def _base_660_filtrada() -> pd.DataFrame:
    """Shared base for every 660-family table below: own-brand sales
    (MARCA_PROPRIA==1) with TIPO_REGISTRO starting with "VENDA", joined
    with the pre-computed sale type (tipo_venda.parquet, by [ID_VENDA,
    PRODUTO] - a sale can have more than one product line, and ID_VENDA
    ALONE is not unique in either table; merging on ID_VENDA alone fans
    out any multi-line sale M x N instead of 1:1, silently inflating every
    total - bug caught and fixed before trusting any number from this
    module, confirmed against the real data: 0 duplicates on
    [ID_VENDA, PRODUTO] in both tables, vs 1,590 duplicated ID_VENDA
    values alone). Blank NOME_BLOCO/CRM - UF/VENDEDOR become NOT_INFORMED
    (groupby drops NaN keys by default - without this, revenue with no
    resolved block would silently disappear from every block-grouped
    summary)."""
    vendas = _ler("vendas_660")
    tipo_venda = _ler("tipo_venda")[["ID_VENDA", "PRODUTO", "TIPO_VENDA"]]

    base = vendas[_eh_venda(vendas["TIPO_REGISTRO"]) & (vendas["MARCA_PROPRIA"] == 1)].copy()
    base = base.merge(tipo_venda, on=["ID_VENDA", "PRODUTO"], how="left")

    base["block"] = base["NOME_BLOCO"].fillna(NOT_INFORMED)
    base["sale_type"] = base["TIPO_VENDA"].fillna(NOT_INFORMED)
    base["payment_type"] = base["TIPO_PAGAMENTO"].fillna("UNKNOWN")
    base["client_effort"] = base["ESFORCO_CLIENTE"]
    base["crm_uf"] = base["CRM - UF"].fillna(NOT_INFORMED)
    base["doctor_name"] = base["NOME_MEDICO"].fillna(NOT_INFORMED)
    base["product"] = base["PRODUTO"].fillna(NOT_INFORMED)
    base["vendor"] = base["VENDEDOR"].fillna(NOT_INFORMED)
    base["month"] = base["DATA_VENDA"].dt.to_period("M").dt.to_timestamp()
    # new_patient_id = ID_CLIENTE only on a patient's FIRST purchase row
    # (PRIMEIRA_CLIENTE=="1"), NaN otherwise - nunique() then counts only
    # the new ones (new_patients metric below).
    base["new_patient_id"] = base["ID_CLIENTE"].where(base["PRIMEIRA_CLIENTE"] == "1")
    return base


_METRIC_AGG = {
    "revenue": ("FATURAMENTO", "sum"),
    "order_count": ("ID_VENDA", "nunique"),
    "units": ("QUANTIDADE", "sum"),
    "new_patients": ("new_patient_id", "nunique"),
}


def _filter_effort_payment(base: pd.DataFrame, client_effort: str, payment_type: str) -> pd.DataFrame:
    if client_effort == "Yes":
        base = base[base["client_effort"] == "1"]
    if payment_type == "Own Funds":
        base = base[base["payment_type"] == "RECURSO PROPRIO"]
    elif payment_type == "Legal":
        base = base[base["payment_type"] == "JUDICIAL"]
    return base


def _filter_block(base: pd.DataFrame, block: str | None) -> pd.DataFrame:
    return base if block is None else base[base["block"] == block]


@dataclass
class Data660:
    sales: pd.DataFrame            # block, month, client_effort, payment_type, 4 metrics
    sales_by_sale_type: pd.DataFrame      # + sale_type
    sales_by_doctor: pd.DataFrame         # block, crm_uf, doctor_name, month, client_effort, payment_type, sale_type, 4 metrics
    sales_by_product: pd.DataFrame        # block, crm_uf, doctor_name, product, month, client_effort, payment_type, 4 metrics


def load_data_660() -> Data660:
    base = _base_660_filtrada()
    sales = base.groupby(["block", "month", "client_effort", "payment_type"]).agg(**_METRIC_AGG).reset_index()
    sales_by_sale_type = base.groupby(
        ["block", "month", "client_effort", "payment_type", "sale_type"]
    ).agg(**_METRIC_AGG).reset_index()
    sales_by_doctor = base.groupby(
        ["block", "crm_uf", "doctor_name", "month", "client_effort", "payment_type", "sale_type"]
    ).agg(**_METRIC_AGG).reset_index()
    sales_by_product = base.groupby(
        ["block", "crm_uf", "doctor_name", "product", "month", "client_effort", "payment_type"]
    ).agg(**_METRIC_AGG).reset_index()
    return Data660(sales, sales_by_sale_type, sales_by_doctor, sales_by_product)


def blocks_available(data: Data660) -> list[str]:
    return sorted(data.sales["block"].dropna().unique())


def months_available(data: Data660) -> list[pd.Timestamp]:
    return sorted(data.sales["month"].dropna().unique())


def sale_types_available(data: Data660) -> list[str]:
    return sorted(data.sales_by_doctor["sale_type"].dropna().unique())


# --- Month selection ("top months") - ported from RecorteMeses/
# _aplicar_recorte_vetorizado. "all" (default) uses every month in the
# window; "top_n"/"top_pct" restrict the mean/median to the K months of
# HIGHEST value in the window - a benchmark against the best months
# instead of a plain average. ---

@dataclass(frozen=True)
class MonthSelection:
    kind: str  # "all" | "top_n" | "top_pct"
    value: float | None = None


def _effective_k(selection: MonthSelection | None, available: int) -> int | None:
    if selection is None or selection.kind == "all" or available <= 0:
        return None
    if selection.kind == "top_n":
        return max(1, min(int(selection.value), available))
    if selection.kind == "top_pct":
        return max(1, min(math.ceil(selection.value / 100 * available), available))
    raise ValueError(f"Unknown MonthSelection.kind: {selection.kind!r}")


def _current_period_start(current_month: pd.Timestamp, months_in_current_period: int) -> pd.Timestamp:
    """1st month of the "current period" (the chosen month + the
    months_in_current_period-1 months BEFORE it, inclusive). Also used as
    the new "end" passed to _benchmark() instead of current_month - the
    benchmark window ends BEFORE the whole current period (not just before
    current_month), so current-period months never also land inside the
    benchmark (double counting). months_in_current_period=1 returns
    current_month unchanged."""
    return current_month - pd.DateOffset(months=months_in_current_period - 1)


def _current_period_value(monthly_series: pd.Series, current_month: pd.Timestamp, months_in_current_period: int, measure: str) -> float:
    start = _current_period_start(current_month, months_in_current_period)
    months = pd.date_range(start, current_month, freq="MS")
    values = monthly_series.reindex(months).fillna(0.0)
    return float(values.mean()) if measure == "Mean" else float(values.median())


def _benchmark(monthly_series: pd.Series, end_month: pd.Timestamp, n_months: int | None, measure: str, selection: MonthSelection | None = None) -> float | None:
    """Mean/median of the n_months BEFORE end_month (never includes
    end_month). Month with no data inside the window counts as 0.
    Quarter/Semester/Year/Last 3 Years: fixed calendar window, always
    filled. Historical (n_months=None): starts at the series' own FIRST
    data point - returns None ("no history") only when the series has no
    month before end_month at all."""
    if n_months is None:
        months_with_data = monthly_series.index[monthly_series.index < end_month]
        if months_with_data.empty:
            return None
        start = months_with_data.min()
        window = pd.date_range(start, end_month - pd.DateOffset(months=1), freq="MS")
    else:
        window = pd.date_range(end_month - pd.DateOffset(months=n_months), periods=n_months, freq="MS")
    values = monthly_series.reindex(window).fillna(0)
    if values.empty:
        return None
    k = _effective_k(selection, len(values))
    if k is not None:
        values = values.nlargest(k)
    return float(values.mean()) if measure == "Mean" else float(values.median())


def classify_deviation(current_value: float, benchmark: float | None) -> str:
    """% deviation = (current - benchmark) / benchmark * 100. benchmark=0
    and current>0 -> "MUCH ABOVE"; |deviation%|<=10% -> "NEUTRAL"; <=25% ->
    "SLIGHTLY ABOVE/BELOW"; <=40% -> "ABOVE/BELOW"; >40% -> "MUCH
    ABOVE/BELOW". benchmark=None -> "NO HISTORY"."""
    if benchmark is None:
        return "NO HISTORY"
    if benchmark == 0:
        return "NEUTRAL" if current_value == 0 else "MUCH ABOVE"
    deviation_pct = (current_value - benchmark) / benchmark * 100
    if abs(deviation_pct) <= 10:
        return "NEUTRAL"
    sufixo = "ABOVE" if deviation_pct > 0 else "BELOW"
    if abs(deviation_pct) <= 25:
        return f"SLIGHTLY {sufixo}"
    if abs(deviation_pct) <= 40:
        return sufixo
    return f"MUCH {sufixo}"


def _rows_per_metric(monthly: pd.DataFrame, current_month: pd.Timestamp, n_months: int | None, measure: str, selection: MonthSelection | None = None, months_in_current_period: int = 1) -> list[dict]:
    benchmark_end = _current_period_start(current_month, months_in_current_period)
    rows = []
    for metric in METRICS:
        series = monthly[metric] if metric in monthly.columns else pd.Series(dtype=float, index=pd.DatetimeIndex([]))
        current_value = _current_period_value(series, current_month, months_in_current_period, measure)
        benchmark = _benchmark(series, benchmark_end, n_months, measure, selection)
        rows.append({
            "metric": metric, "current_value": current_value, "benchmark": benchmark,
            "classification": classify_deviation(current_value, benchmark),
        })
    return rows


def calculate_table_660(data: Data660, block: str | None, client_effort: str, payment_type: str, current_month: pd.Timestamp, window: str, measure: str, selection: MonthSelection | None = None, months_in_current_period: int = 1) -> pd.DataFrame:
    base = _filter_effort_payment(_filter_block(data.sales, block), client_effort, payment_type)
    monthly = base.groupby("month")[METRICS].sum()
    n_months = BENCHMARK_WINDOWS[window]
    return pd.DataFrame(_rows_per_metric(monthly, current_month, n_months, measure, selection, months_in_current_period))


def calculate_table_by_sale_type(data: Data660, block: str | None, client_effort: str, payment_type: str, current_month: pd.Timestamp, window: str, measure: str, metric: str, selection: MonthSelection | None = None, months_in_current_period: int = 1) -> pd.DataFrame:
    base = _filter_effort_payment(_filter_block(data.sales_by_sale_type, block), client_effort, payment_type)
    n_months = BENCHMARK_WINDOWS[window]
    benchmark_end = _current_period_start(current_month, months_in_current_period)
    rows = []
    for sale_type, group in base.groupby("sale_type"):
        monthly = group.groupby("month")[METRICS].sum()
        series = monthly[metric] if metric in monthly.columns else pd.Series(dtype=float, index=pd.DatetimeIndex([]))
        current_value = _current_period_value(series, current_month, months_in_current_period, measure)
        benchmark = _benchmark(series, benchmark_end, n_months, measure, selection)
        difference = None if benchmark is None else current_value - benchmark
        rows.append({
            "sale_type": sale_type, "current_value": current_value, "benchmark": benchmark,
            "difference": difference, "classification": classify_deviation(current_value, benchmark),
        })
    if not rows:
        return pd.DataFrame(columns=["sale_type", "current_value", "benchmark", "difference", "classification"])
    return pd.DataFrame(rows).sort_values("difference").reset_index(drop=True)


def _apply_selection_vectorized(values: pd.DataFrame, measure: str, selection: MonthSelection) -> pd.Series:
    """Vectorized version of _effective_k + nlargest for THOUSANDS of
    series at once (By Doctor). `values`: index=series key, columns=months
    in the window, NaN=outside the window, 0=inside but no row that
    month."""
    arr = values.to_numpy()
    valid = ~np.isnan(arr)
    available = valid.sum(axis=1)
    if selection.kind == "top_n":
        k = np.minimum(int(selection.value), available)
    else:
        k = np.ceil(selection.value / 100 * available).astype(np.int64)
    k = np.clip(k, 1, np.maximum(available, 1))
    k[available == 0] = 0
    ranked = np.where(valid, arr, -np.inf)
    rank_desc = np.argsort(np.argsort(-ranked, axis=1), axis=1)
    within_top_k = rank_desc < k[:, None]
    masked = np.where(within_top_k & valid, arr, np.nan)
    with np.errstate(invalid="ignore"):
        result = np.nanmean(masked, axis=1) if measure == "Mean" else np.nanmedian(masked, axis=1)
    out = pd.Series(result, index=values.index)
    out[available == 0] = np.nan
    return out


def _current_period_value_vectorized(wide: pd.DataFrame, current_month: pd.Timestamp, months_in_current_period: int, measure: str) -> pd.Series:
    cols = pd.date_range(_current_period_start(current_month, months_in_current_period), periods=months_in_current_period, freq="MS")
    values = wide.reindex(columns=cols).fillna(0.0)
    return values.mean(axis=1) if measure == "Mean" else values.median(axis=1)


def _benchmark_vectorized(wide: pd.DataFrame, end_month: pd.Timestamp, n_months: int | None, measure: str, selection: MonthSelection | None = None) -> pd.Series:
    agg = "mean" if measure == "Mean" else "median"
    if n_months is not None:
        cols = pd.date_range(end_month - pd.DateOffset(months=n_months), periods=n_months, freq="MS")
        values = wide.reindex(columns=cols).fillna(0.0)
        if selection is None or selection.kind == "all":
            return values.agg(agg, axis=1)
        return _apply_selection_vectorized(values, measure, selection)

    months_before = [c for c in wide.columns if c < end_month]
    if not months_before:
        return pd.Series(np.nan, index=wide.index)
    cols_hist = pd.date_range(min(months_before), end_month - pd.DateOffset(months=1), freq="MS")
    block = wide.reindex(columns=cols_hist)
    notna = block.notna().to_numpy()
    has_any = notna.any(axis=1)
    cols_ns = np.array([c.value for c in block.columns], dtype="int64")
    first_ns = np.where(has_any, cols_ns[notna.argmax(axis=1)], np.iinfo("int64").max)
    before_start = cols_ns[None, :] < first_ns[:, None]
    values = block.fillna(0.0).mask(before_start)
    if selection is None or selection.kind == "all":
        result = values.agg(agg, axis=1)
    else:
        result = _apply_selection_vectorized(values, measure, selection)
    result[~has_any] = np.nan
    return result


def calculate_table_by_doctor(data: Data660, block: str | None, client_effort: str, payment_type: str, sale_type: str | None, current_month: pd.Timestamp, window: str, measure: str, metric: str, selection: MonthSelection | None = None, months_in_current_period: int = 1) -> pd.DataFrame:
    """One row per doctor, grouped ONLY by crm_uf (never by block/name
    spelling) - same lesson learned in classificacao_vendas (a doctor can
    move between blocks, or have a name recorded slightly differently
    over time): grouping by block too would split one real doctor's
    history into disconnected rows. "blocks" column (comma-joined list)
    replaces a single "block" column for that reason."""
    base = _filter_effort_payment(_filter_block(data.sales_by_doctor, block), client_effort, payment_type)
    if sale_type is not None:
        base = base[base["sale_type"] == sale_type]
    columns = ["doctor_name", "crm_uf", "blocks", "current_value", "benchmark", "difference", "classification"]
    if base.empty:
        return pd.DataFrame(columns=columns)

    n_months = BENCHMARK_WINDOWS[window]
    wide = base.pivot_table(index="crm_uf", columns="month", values=metric, aggfunc="sum")
    current_value = _current_period_value_vectorized(wide, current_month, months_in_current_period, measure)
    benchmark_end = _current_period_start(current_month, months_in_current_period)
    benchmark = _benchmark_vectorized(wide, benchmark_end, n_months, measure, selection)

    info = base.sort_values("month").groupby("crm_uf").agg(
        doctor_name=("doctor_name", "last"), blocks=("block", lambda s: ", ".join(sorted(s.unique()))),
    )
    out = pd.DataFrame({"current_value": current_value, "benchmark": benchmark}).reset_index()
    out["difference"] = out["current_value"] - out["benchmark"]
    out["classification"] = [
        classify_deviation(v, None if pd.isna(b) else b) for v, b in zip(out["current_value"], out["benchmark"])
    ]
    out = out.merge(info, on="crm_uf", how="left")
    return out[columns].sort_values("difference").reset_index(drop=True)


def calculate_table_by_product(data: Data660, crm_uf: str, client_effort: str, payment_type: str, current_month: pd.Timestamp, window: str, measure: str, metric: str, selection: MonthSelection | None = None, months_in_current_period: int = 1) -> pd.DataFrame:
    """One row per product, restricted to ONE doctor (CRM-UF search, exact
    but case/space-insensitive) - ignores the page's "Block" segmenter on
    purpose (sums every block where that CRM-UF appears)."""
    columns = ["product", "current_value", "benchmark", "difference", "classification"]
    crm_normalized = (crm_uf or "").strip().upper()
    if not crm_normalized:
        return pd.DataFrame(columns=columns)

    base = _filter_effort_payment(data.sales_by_product, client_effort, payment_type)
    base = base[base["crm_uf"].str.upper() == crm_normalized]
    if base.empty:
        return pd.DataFrame(columns=columns)

    n_months = BENCHMARK_WINDOWS[window]
    wide = base.pivot_table(index="product", columns="month", values=metric, aggfunc="sum")
    current_value = _current_period_value_vectorized(wide, current_month, months_in_current_period, measure)
    benchmark_end = _current_period_start(current_month, months_in_current_period)
    benchmark = _benchmark_vectorized(wide, benchmark_end, n_months, measure, selection)

    out = pd.DataFrame({"current_value": current_value, "benchmark": benchmark}).reset_index()
    out = out.rename(columns={"index": "product"})
    out["difference"] = out["current_value"] - out["benchmark"]
    out["classification"] = [
        classify_deviation(v, None if pd.isna(b) else b) for v, b in zip(out["current_value"], out["benchmark"])
    ]
    return out[columns].sort_values("difference").reset_index(drop=True)


# =============================================================================
# Churns in the Month - reads the pre-computed CHURN/DATA_RUPTURA/
# POSOLOGIA_SUSPEITA columns from carteira_pacientes.parquet (see module
# docstring) instead of re-deriving the stock-rupture projection.
# =============================================================================

@dataclass
class DataChurns:
    patients: pd.DataFrame  # client_id, product, block, payment_type, vendor, crm_uf, churn_month, posologia_suspeita


def load_data_churns() -> DataChurns:
    carteira = _ler("carteira_pacientes")
    # merge key is [ID_VENDA, PRODUTO], NOT ID_VENDA alone - same fan-out
    # bug caught and fixed in _base_660_filtrada above applies here too
    # (carteira_pacientes has 1,497 ID_VENDA values with more than one
    # row - multi-product sales - but 0 duplicates on [ID_VENDA, PRODUTO]).
    sales = _ler("vendas_660")[[
        "ID_VENDA", "PRODUTO", "NOME_BLOCO", "TIPO_PAGAMENTO", "VENDEDOR", "CRM - UF",
    ]].rename(columns={
        "NOME_BLOCO": "block", "TIPO_PAGAMENTO": "payment_type", "VENDEDOR": "vendor", "CRM - UF": "crm_uf",
    })
    churned = carteira[carteira["CHURN"] == True].copy()  # noqa: E712 - pandas nullable boolean, == True is intentional (is True would not broadcast)
    churned = churned.merge(sales, on=["ID_VENDA", "PRODUTO"], how="left")
    churned["block"] = churned["block"].fillna(NOT_INFORMED)
    churned["crm_uf"] = churned["crm_uf"].fillna(NOT_INFORMED)
    churned["payment_type"] = churned["payment_type"].fillna("UNKNOWN")
    churned["churn_month"] = churned["DATA_RUPTURA"].dt.to_period("M").dt.to_timestamp()
    churned = churned.rename(columns={"ID_PACIENTE": "client_id", "PRODUTO": "product", "POSOLOGIA_SUSPEITA": "posologia_suspeita"})
    return DataChurns(churned[[
        "client_id", "product", "block", "payment_type", "vendor", "crm_uf", "churn_month", "posologia_suspeita",
    ]])


def products_available_churns(data: DataChurns) -> list[str]:
    return sorted(data.patients["product"].dropna().unique())


def blocks_available_churns(data: DataChurns) -> list[str]:
    return sorted(data.patients["block"].dropna().unique())


def calculate_churns_in_month(data: DataChurns, month: pd.Timestamp, product: str | None, block: str | None, payment_type: str) -> dict:
    """churn_count: distinct patients whose projected rupture falls in
    `month` and whose POSOLOGIA_SUSPEITA is NOT True (excludes the single
    upstream outlier tier - see module docstring, only one tier exists now
    vs the old 1.5x/3x pair). table: ID Patient/Vendor/CRM-UF, superset of
    churn_count, one row per patient."""
    sel = data.patients[data.patients["churn_month"] == month]
    if product is not None:
        sel = sel[sel["product"] == product]
    if block is not None:
        sel = sel[sel["block"] == block]
    if payment_type == "Own Funds":
        sel = sel[sel["payment_type"] == "RECURSO PROPRIO"]
    elif payment_type == "Legal":
        sel = sel[sel["payment_type"] == "JUDICIAL"]

    table = (
        sel[["client_id", "vendor", "crm_uf"]].drop_duplicates("client_id")
        .rename(columns={"client_id": "patient_id"}).reset_index(drop=True)
    )
    return {
        "churn_count": int(sel.loc[sel["posologia_suspeita"] != True, "client_id"].nunique()),  # noqa: E712
        "table": table,
    }


# =============================================================================
# Rises and Drops - ranks the biggest deviations of 660 Analysis, across
# ALL blocks at once. Two base tables (without/with sale type breakdown),
# same classify_deviation/benchmark logic as 660 Analysis.
# =============================================================================

def calculate_table_by_block_and_sale_type(data: Data660, client_effort: str, payment_type: str, current_month: pd.Timestamp, window: str, measure: str, selection: MonthSelection | None = None, months_in_current_period: int = 1) -> pd.DataFrame:
    base = _filter_effort_payment(data.sales_by_sale_type, client_effort, payment_type)
    n_months = BENCHMARK_WINDOWS[window]
    rows = []
    for (block, sale_type), group in base.groupby(["block", "sale_type"]):
        monthly = group.groupby("month")[METRICS].sum()
        for row in _rows_per_metric(monthly, current_month, n_months, measure, selection, months_in_current_period):
            rows.append({"block": block, "sale_type": sale_type, **row})
    if not rows:
        return pd.DataFrame(columns=["block", "sale_type", "metric", "current_value", "benchmark", "classification"])
    return pd.DataFrame(rows)


def calculate_table_by_block(data: Data660, client_effort: str, payment_type: str, current_month: pd.Timestamp, window: str, measure: str, selection: MonthSelection | None = None, months_in_current_period: int = 1) -> pd.DataFrame:
    base = _filter_effort_payment(data.sales, client_effort, payment_type)
    n_months = BENCHMARK_WINDOWS[window]
    rows = []
    for block, group in base.groupby("block"):
        monthly = group.groupby("month")[METRICS].sum()
        for row in _rows_per_metric(monthly, current_month, n_months, measure, selection, months_in_current_period):
            rows.append({"block": block, **row})
    if not rows:
        return pd.DataFrame(columns=["block", "metric", "current_value", "benchmark", "classification"])
    return pd.DataFrame(rows)


def calculate_base_table(data: Data660, client_effort: str, payment_type: str, current_month: pd.Timestamp, window: str, measure: str, metric: str, selection: MonthSelection | None = None, months_in_current_period: int = 1) -> pd.DataFrame:
    table = calculate_table_by_block_and_sale_type(data, client_effort, payment_type, current_month, window, measure, selection, months_in_current_period)
    return table[table["metric"] == metric].reset_index(drop=True)


def calculate_base_table_by_block(data: Data660, client_effort: str, payment_type: str, current_month: pd.Timestamp, window: str, measure: str, metric: str, selection: MonthSelection | None = None, months_in_current_period: int = 1) -> pd.DataFrame:
    table = calculate_table_by_block(data, client_effort, payment_type, current_month, window, measure, selection, months_in_current_period)
    return table[table["metric"] == metric].reset_index(drop=True)


def _rank(table: pd.DataFrame, suffix: str, magnitude, cutoff_pct: float | None) -> pd.DataFrame:
    filtered = table[table["classification"].str.endswith(suffix)].copy()
    if filtered.empty:
        return filtered.assign(percentage=pd.Series(dtype=float))
    filtered["magnitude"] = magnitude(filtered["current_value"], filtered["benchmark"])
    total = filtered["magnitude"].sum()
    filtered["percentage"] = filtered["magnitude"] / total * 100
    if cutoff_pct is not None:
        filtered = filtered[filtered["percentage"] >= cutoff_pct]
    return filtered.sort_values("percentage", ascending=False).reset_index(drop=True)


def drops(base_table: pd.DataFrame, cutoff_pct: float | None) -> pd.DataFrame:
    return _rank(base_table, "BELOW", lambda current, benchmark: benchmark - current, cutoff_pct)


def rises(base_table: pd.DataFrame, cutoff_pct: float | None) -> pd.DataFrame:
    return _rank(base_table, "ABOVE", lambda current, benchmark: current - benchmark, cutoff_pct)


# =============================================================================
# Rep Block Performance - Doctor Potential (only section ported - no
# Supabase cross-reference: Effort is classified LOCALLY from painel.
# parquet's DIAS_SEM_VISITA_NUM, Reason stays blank for now, see module
# docstring and README.md).
# =============================================================================

DAYS_RECENT_VISIT = 90
EFFORTS = ["All", "Outside Panel", "Never Visited", "Visited", "Visited Recently"]
RESULTS = ["All", "No Result", "With Result"]


def _is_isolate(product: str) -> bool:
    return str(product).upper().startswith("CANABIDIOL") or str(product).upper().startswith("ISOLATE")


@dataclass
class DataDoctorPotential:
    px_doctor: pd.DataFrame     # block, crm_uf, product_type, laboratory, doctor_name, px (most recent MAT)
    px_product: pd.DataFrame    # crm_uf, product, laboratory, product_type, px
    revenue_1015: pd.DataFrame  # crm_uf, block, month, revenue (VALOR_REPRESENTANTE)
    panel: pd.DataFrame         # crm_uf, days_since_visit (NaN = never visited)
    mat_anchor: pd.Timestamp | None


def _most_recent_mat(per_nome: pd.Series) -> tuple[str | None, pd.Timestamp | None]:
    """Finds the most recent PER_NOME ("MAT MM/AA") among the distinct
    values in the column - returns (original_value, anchor_month) or
    (None, None) if there is no recognizable PER_NOME at all."""
    import re
    pattern = re.compile(r"(\d{2})/(\d{2})")
    dates = {}
    for periodo in per_nome.dropna().unique():
        match = pattern.search(str(periodo))
        if match:
            month, year = int(match.group(1)), int(match.group(2))
            dates[periodo] = pd.Timestamp(year=2000 + year, month=month, day=1)
    if not dates:
        return None, None
    current_period = max(dates, key=dates.get)
    return current_period, dates[current_period]


def load_data_doctor_potential() -> DataDoctorPotential:
    closeup = _ler("closeup")
    current_period, mat_anchor = _most_recent_mat(closeup["PER_NOME"])
    current = closeup if current_period is None else closeup[closeup["PER_NOME"] == current_period]

    current = current.copy()
    current["block"] = current["NOME_BLOCO"].fillna(NOT_INFORMED)
    current["crm_uf"] = current["CRM - UF"].fillna(NOT_INFORMED)
    current["product_type"] = np.where(current["PRODUTO"].apply(_is_isolate), "Isolate", "Full Spectrum")

    px_doctor = current.groupby(["block", "crm_uf", "product_type", "LABORATORIO"], as_index=False).agg(
        doctor_name=("NOME_MEDICO", "first"), px=("PX", "sum"),
    ).rename(columns={"LABORATORIO": "laboratory"})
    px_product = current.groupby(["crm_uf", "PRODUTO", "LABORATORIO", "product_type"], as_index=False).agg(
        px=("PX", "sum"),
    ).rename(columns={"PRODUTO": "product", "LABORATORIO": "laboratory"})

    v1015 = _ler("vendas_1015").copy()
    v1015["month"] = v1015["DATA"].dt.to_period("M").dt.to_timestamp()
    revenue_1015 = v1015.groupby(["CRM_UF", "BLOCO", "month"], as_index=False)["VALOR_REPRESENTANTE"].sum().rename(
        columns={"CRM_UF": "crm_uf", "BLOCO": "block", "VALOR_REPRESENTANTE": "revenue"},
    )

    panel = _ler("painel")[["CRM - UF", "DIAS_SEM_VISITA_NUM"]].rename(
        columns={"CRM - UF": "crm_uf", "DIAS_SEM_VISITA_NUM": "days_since_visit"},
    )
    return DataDoctorPotential(px_doctor, px_product, revenue_1015, panel, mat_anchor)


def blocks_available_doctor_potential(data: DataDoctorPotential) -> list[str]:
    return sorted(data.px_doctor["block"].dropna().unique())


def laboratories_available_doctor_potential(data: DataDoctorPotential) -> list[str]:
    return sorted(data.px_doctor["laboratory"].dropna().unique())


def _effort_bucket(crm_uf: str, panel_by_crm: dict[str, float]) -> str:
    """"Outside Panel": crm_uf absent from painel.parquet entirely. "Never
    Visited": in the panel, DIAS_SEM_VISITA_NUM blank. "Visited": in the
    panel, more than DAYS_RECENT_VISIT days since the last visit. "Visited
    Recently": DAYS_RECENT_VISIT days or fewer. Mutually exclusive - every
    doctor falls into exactly one."""
    if crm_uf not in panel_by_crm:
        return "Outside Panel"
    days = panel_by_crm[crm_uf]
    if pd.isna(days):
        return "Never Visited"
    return "Visited Recently" if days <= DAYS_RECENT_VISIT else "Visited"


def calculate_table_doctor_potential(data: DataDoctorPotential, block: str | None, laboratory: str | None, product_type: str, effort: str, result: str) -> pd.DataFrame:
    columns = ["doctor_name", "crm_uf", "blocks", "px", "effort", "result", "reason"]
    px = data.px_doctor
    if block is not None:
        px = px[px["block"] == block]
    if laboratory is not None:
        px = px[px["laboratory"] == laboratory]
    if product_type != "All":
        px = px[px["product_type"] == product_type]
    if px.empty:
        return pd.DataFrame(columns=columns)

    by_doctor = px.groupby("crm_uf").agg(
        doctor_name=("doctor_name", "first"), px=("px", "sum"),
        blocks=("block", lambda s: ", ".join(sorted(s.unique()))),
    ).reset_index()

    panel_by_crm = dict(zip(data.panel["crm_uf"], data.panel["days_since_visit"]))
    by_doctor["effort"] = [_effort_bucket(crm, panel_by_crm) for crm in by_doctor["crm_uf"]]

    if data.mat_anchor is None:
        by_doctor["result"] = 0.0
    else:
        window_start = data.mat_anchor - pd.DateOffset(months=11)
        window_end = data.mat_anchor + pd.DateOffset(months=1)
        rev = data.revenue_1015
        rev_window = rev[(rev["month"] >= window_start) & (rev["month"] < window_end)]
        rev_by_doctor = rev_window.groupby("crm_uf", as_index=False)["revenue"].sum()
        by_doctor = by_doctor.merge(rev_by_doctor, on="crm_uf", how="left")
        by_doctor["result"] = by_doctor["revenue"].fillna(0.0)

    if effort != "All":
        by_doctor = by_doctor[by_doctor["effort"] == effort]
    if result == "No Result":
        by_doctor = by_doctor[by_doctor["result"] == 0]
    elif result == "With Result":
        by_doctor = by_doctor[by_doctor["result"] > 0]

    by_doctor["reason"] = ""  # no local source yet for this - see module docstring.
    return by_doctor[columns].sort_values("px", ascending=False).reset_index(drop=True)


def calculate_products_doctor_potential(data: DataDoctorPotential, crm_uf: str) -> pd.DataFrame:
    columns = ["product", "laboratory", "product_type", "px"]
    crm_normalized = (crm_uf or "").strip().upper()
    if not crm_normalized:
        return pd.DataFrame(columns=columns)
    found = data.px_product[data.px_product["crm_uf"].str.upper() == crm_normalized]
    return found[columns].sort_values("px", ascending=False).reset_index(drop=True)
